modLoader="javafml"
loaderVersion="[4,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="the_quiet_between"
version="0.0.2"
displayName="The Quiet Between"
displayURL="https://mcreator.net"
logoFile="logo.png"
credits="Created By Single Dev: VoidSignalDev"
authors="VoidSignalDev"
description="what are you doing here"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "the_quiet_between.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.the_quiet_between]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.155,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.the_quiet_between]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration